name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4  # Updated version

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1.0.3  # Specify version
        with:
          host: 13.233.103.237
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          passphrase: ${{ secrets.PHRASE }}
          port: 22
          script: |
            whoami
            pwd
